version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=playbook_user
      - POSTGRES_PASSWORD=playbook_password
      - POSTGRES_DB=playbook
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    restart: on-failure 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev