version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile.dev
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev