# Use the official Microsoft .NET Core SDK as a build image
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env

# Set the working directory in the container
WORKDIR /app

# Copy the project file to the container
COPY *.csproj ./

# Restore the project dependencies
RUN dotnet restore

# Copy the remaining files to the container
COPY . ./

# Build the application
RUN dotnet publish -c Release -o out

# Use the official Microsoft .NET Core runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0

# Set the working directory in the container
WORKDIR /app

# Copy the published application from the build environment
COPY --from=build-env /app/out .

# Define the entry point for the container
ENTRYPOINT ["dotnet", "orchestrator.dll"]
